[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "XmlDict"
version="1.1.2"
description="XML JSON conversion"
authors = [
  { name="Daniel Rexin", email="daniel@medinion.de" },
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
]

# [project.urls]
# Homepage =
# Issues =
